//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Action) DeepCopyInto(out *Action) {
	*out = *in
	if in.Delay != nil {
		in, out := &in.Delay, &out.Delay
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Workload != nil {
		in, out := &in.Workload, &out.Workload
		*out = new(WorkloadAction)
		(*in).DeepCopyInto(*out)
	}
	if in.Scale != nil {
		in, out := &in.Scale, &out.Scale
		*out = new(ScaleAction)
		**out = **in
	}
	if in.DeployImage != nil {
		in, out := &in.DeployImage, &out.DeployImage
		*out = new(DeployImageAction)
		(*in).DeepCopyInto(*out)
	}
	if in.ChaosMesh != nil {
		in, out := &in.ChaosMesh, &out.ChaosMesh
		*out = new(ChaosMeshAction)
		(*in).DeepCopyInto(*out)
	}
	if in.DBExec != nil {
		in, out := &in.DBExec, &out.DBExec
		*out = new(DBExecAction)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Action.
func (in *Action) DeepCopy() *Action {
	if in == nil {
		return nil
	}
	out := new(Action)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveAction) DeepCopyInto(out *ActiveAction) {
	*out = *in
	if in.AppliedAt != nil {
		in, out := &in.AppliedAt, &out.AppliedAt
		*out = (*in).DeepCopy()
	}
	in.Revert.DeepCopyInto(&out.Revert)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveAction.
func (in *ActiveAction) DeepCopy() *ActiveAction {
	if in == nil {
		return nil
	}
	out := new(ActiveAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChaosMeshAction) DeepCopyInto(out *ChaosMeshAction) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChaosMeshAction.
func (in *ChaosMeshAction) DeepCopy() *ChaosMeshAction {
	if in == nil {
		return nil
	}
	out := new(ChaosMeshAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CurrentRun) DeepCopyInto(out *CurrentRun) {
	*out = *in
	in.StartedAt.DeepCopyInto(&out.StartedAt)
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CurrentRun.
func (in *CurrentRun) DeepCopy() *CurrentRun {
	if in == nil {
		return nil
	}
	out := new(CurrentRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DBExecAction) DeepCopyInto(out *DBExecAction) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Ensure != nil {
		in, out := &in.Ensure, &out.Ensure
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Revert != nil {
		in, out := &in.Revert, &out.Revert
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DBExecAction.
func (in *DBExecAction) DeepCopy() *DBExecAction {
	if in == nil {
		return nil
	}
	out := new(DBExecAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeployImageAction) DeepCopyInto(out *DeployImageAction) {
	*out = *in
	out.TargetRef = in.TargetRef
	if in.RolloutTimeout != nil {
		in, out := &in.RolloutTimeout, &out.RolloutTimeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeployImageAction.
func (in *DeployImageAction) DeepCopy() *DeployImageAction {
	if in == nil {
		return nil
	}
	out := new(DeployImageAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailureScenario) DeepCopyInto(out *FailureScenario) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailureScenario.
func (in *FailureScenario) DeepCopy() *FailureScenario {
	if in == nil {
		return nil
	}
	out := new(FailureScenario)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FailureScenario) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailureScenarioList) DeepCopyInto(out *FailureScenarioList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FailureScenario, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailureScenarioList.
func (in *FailureScenarioList) DeepCopy() *FailureScenarioList {
	if in == nil {
		return nil
	}
	out := new(FailureScenarioList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FailureScenarioList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailureScenarioSpec) DeepCopyInto(out *FailureScenarioSpec) {
	*out = *in
	if in.ExpectedSymptoms != nil {
		in, out := &in.ExpectedSymptoms, &out.ExpectedSymptoms
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Trigger != nil {
		in, out := &in.Trigger, &out.Trigger
		*out = new(TriggerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]Action, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailureScenarioSpec.
func (in *FailureScenarioSpec) DeepCopy() *FailureScenarioSpec {
	if in == nil {
		return nil
	}
	out := new(FailureScenarioSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailureScenarioStatus) DeepCopyInto(out *FailureScenarioStatus) {
	*out = *in
	if in.CurrentRun != nil {
		in, out := &in.CurrentRun, &out.CurrentRun
		*out = new(CurrentRun)
		(*in).DeepCopyInto(*out)
	}
	if in.ActiveActions != nil {
		in, out := &in.ActiveActions, &out.ActiveActions
		*out = make([]ActiveAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.History != nil {
		in, out := &in.History, &out.History
		*out = make([]RunHistoryEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailureScenarioStatus.
func (in *FailureScenarioStatus) DeepCopy() *FailureScenarioStatus {
	if in == nil {
		return nil
	}
	out := new(FailureScenarioStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunHistoryEntry) DeepCopyInto(out *RunHistoryEntry) {
	*out = *in
	in.StartedAt.DeepCopyInto(&out.StartedAt)
	if in.EndedAt != nil {
		in, out := &in.EndedAt, &out.EndedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunHistoryEntry.
func (in *RunHistoryEntry) DeepCopy() *RunHistoryEntry {
	if in == nil {
		return nil
	}
	out := new(RunHistoryEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleAction) DeepCopyInto(out *ScaleAction) {
	*out = *in
	out.TargetRef = in.TargetRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleAction.
func (in *ScaleAction) DeepCopy() *ScaleAction {
	if in == nil {
		return nil
	}
	out := new(ScaleAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleTargetRef) DeepCopyInto(out *ScaleTargetRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleTargetRef.
func (in *ScaleTargetRef) DeepCopy() *ScaleTargetRef {
	if in == nil {
		return nil
	}
	out := new(ScaleTargetRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TriggerSpec) DeepCopyInto(out *TriggerSpec) {
	*out = *in
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TriggerSpec.
func (in *TriggerSpec) DeepCopy() *TriggerSpec {
	if in == nil {
		return nil
	}
	out := new(TriggerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadAction) DeepCopyInto(out *WorkloadAction) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Queries != nil {
		in, out := &in.Queries, &out.Queries
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DeadlineMargin != nil {
		in, out := &in.DeadlineMargin, &out.DeadlineMargin
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadAction.
func (in *WorkloadAction) DeepCopy() *WorkloadAction {
	if in == nil {
		return nil
	}
	out := new(WorkloadAction)
	in.DeepCopyInto(out)
	return out
}
