// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/recommendation.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRecommendationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendationsRequest) Reset() {
	*x = GetRecommendationsRequest{}
	mi := &file_proto_recommendation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendationsRequest) ProtoMessage() {}

func (x *GetRecommendationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recommendation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendationsRequest.ProtoReflect.Descriptor instead.
func (*GetRecommendationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_recommendation_proto_rawDescGZIP(), []int{0}
}

func (x *GetRecommendationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetRecommendationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetRecommendationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductIds    []string               `protobuf:"bytes,1,rep,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendationsResponse) Reset() {
	*x = GetRecommendationsResponse{}
	mi := &file_proto_recommendation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendationsResponse) ProtoMessage() {}

func (x *GetRecommendationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recommendation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendationsResponse.ProtoReflect.Descriptor instead.
func (*GetRecommendationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_recommendation_proto_rawDescGZIP(), []int{1}
}

func (x *GetRecommendationsResponse) GetProductIds() []string {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

var File_proto_recommendation_proto protoreflect.FileDescriptor

const file_proto_recommendation_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/recommendation.proto\x12\x0erecommendation\"J\n" +
	"\x19GetRecommendationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"=\n" +
	"\x1aGetRecommendationsResponse\x12\x1f\n" +
	"\vproduct_ids\x18\x01 \x03(\tR\n" +
	"productIds2\x84\x01\n" +
	"\x15RecommendationService\x12k\n" +
	"\x12GetRecommendations\x12).recommendation.GetRecommendationsRequest\x1a*.recommendation.GetRecommendationsResponseBAZ?github.com/coroot/rca-lab/services/recommendation-service/protob\x06proto3"

var (
	file_proto_recommendation_proto_rawDescOnce sync.Once
	file_proto_recommendation_proto_rawDescData []byte
)

func file_proto_recommendation_proto_rawDescGZIP() []byte {
	file_proto_recommendation_proto_rawDescOnce.Do(func() {
		file_proto_recommendation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_recommendation_proto_rawDesc), len(file_proto_recommendation_proto_rawDesc)))
	})
	return file_proto_recommendation_proto_rawDescData
}

var file_proto_recommendation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_recommendation_proto_goTypes = []any{
	(*GetRecommendationsRequest)(nil),  // 0: recommendation.GetRecommendationsRequest
	(*GetRecommendationsResponse)(nil), // 1: recommendation.GetRecommendationsResponse
}
var file_proto_recommendation_proto_depIdxs = []int32{
	0, // 0: recommendation.RecommendationService.GetRecommendations:input_type -> recommendation.GetRecommendationsRequest
	1, // 1: recommendation.RecommendationService.GetRecommendations:output_type -> recommendation.GetRecommendationsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_recommendation_proto_init() }
func file_proto_recommendation_proto_init() {
	if File_proto_recommendation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_recommendation_proto_rawDesc), len(file_proto_recommendation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_recommendation_proto_goTypes,
		DependencyIndexes: file_proto_recommendation_proto_depIdxs,
		MessageInfos:      file_proto_recommendation_proto_msgTypes,
	}.Build()
	File_proto_recommendation_proto = out.File
	file_proto_recommendation_proto_goTypes = nil
	file_proto_recommendation_proto_depIdxs = nil
}
