#!/usr/bin/env python3
"""Regenerates variants/registry.yaml — the machine-readable map of
bad-deploy image tags to their variant definitions. Run after adding or
changing any services/*/variants/*/variant.yaml."""
import glob
import os

import yaml

entries = []
for f in sorted(glob.glob("services/*/variants/*/variant.yaml")):
    service = f.split(os.sep)[1]
    v = yaml.safe_load(open(f))
    entries.append(
        {
            "image": f"ghcr.io/coroot/rca-lab/{service}:{v['tag']}",
            "service": service,
            "variant": v["name"],
            "summary": v.get("summary", ""),
            "expectedSymptoms": v.get("expected_symptoms", []),
        }
    )

os.makedirs("variants", exist_ok=True)
with open("variants/registry.yaml", "w") as out:
    out.write("# Generated by scripts/gen-variant-registry.py — do not edit.\n")
    yaml.safe_dump({"variants": entries}, out, sort_keys=False)
print(f"wrote variants/registry.yaml ({len(entries)} variants)")
